#!/bin/sh
#
#
#
PATH=$PWD:$PATH

mkdir -p checkdir/master
(cd checkdir/master
 for f in top sub1 sub2
  do
   mkdir $f
   (cd $f
    git init
    date > datelist
    echo $f > packagename
    git add *
    git commit -a -m "Initial files")
  done)

git clone $PWD/checkdir/master/top $PWD/checkdir/slave
cd checkdir/slave
gits inits
gits clones ../sub1 sub1
gits clones ../sub2 sub2
gits checkouts
